In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv(r'/content/txn.csv')

In [7]:
df

,oid,dat,cuid,pay_amount,category,product,city,state,method
0,0,06-26-2011,4007024,40.33,Exercise & Fitness,Cardio Machine Accessories,Clarksville,Tennessee,credit
1,1,05-26-2011,4006742,198.44,Exercise & Fitness,Weightlifting Gloves,Long Beach,California,credit
2,2,06-01-2011,4009775,5.58,Exercise & Fitness,Weightlifting Machine Accessories,Anaheim,California,credit
3,3,06-05-2011,4002199,198.19,Gymnastics,Gymnastics Rings,Milwaukee,Wisconsin,credit
4,4,12-17-2011,4002613,98.81,Team Sports,Field Hockey,Nashville,Tennessee,credit
...,...,...,...,...,...,...,...,...,...
1235,2216,02-21-2011,4008372,43.80,Team Sports,Basketball,Las Vegas,Nevada,credit
1236,2217,01-04-2011,4000247,5.44,Outdoor Play Equipment,Slides,Jersey City,New Jersey,credit
1237,2218,09-13-2011,4001452,119.97,Winter Sports,Downhill Skiing,Denver,Colorado,credit
1238,2219,03-01-2011,4004033,98.22,Water Sports,Windsurfing,Salem,Oregon,credit
1239,2220,07-10-2011,4004649,130.40,Outdoor Recreation,Fishing,Springfield,Illinois,credit

In [13]:
 #jan month oid,cusno,category,product,state
#A. Row count

df1=df.loc[df['dat']<'02-01-2011'][['oid','cuid','category','product','state']]
df1

,oid,cuid,category,product,state
8,8,4007361,Winter Sports,Snowmobiling,Iowa
34,32,4007790,Team Sports,Soccer,Illinois
73,71,4009360,Team Sports,Cricket,Oregon
74,72,4001305,Outdoor Recreation,Skateboarding,Colorado
84,82,4001098,Gymnastics,Gymnastics Rings,Florida
...,...,...,...,...,...
1206,2187,4005541,Games,Dice Games,Utah
1219,2200,4004964,Racquet Sports,Tennis,Pennsylvania
1220,2201,4007645,Exercise & Fitness,Abdominal Equipment,Colorado
1231,2212,4004614,Outdoor Recreation,Running,Massachusetts
1236,2217,4000247,Outdoor Play Equipment,Slides,New Jersey

In [16]:
np.dtype(df['dat'])

dtype('O')

In [28]:
#July Month oid,cusno,category,product,state
#B. Row count
df2=df.loc[(df['dat']>'06-30-2011') & (df['dat']<'08-01-2011')][['oid','cuid','category','product','state']]
df2['category'].count()
df2.shape[0]

91

In [31]:
# Each category [count desc sort]
df1=df.groupby('category')['category'].count().sort_values(ascending=False)
df1

category
Outdoor Recreation        178
Exercise & Fitness        156
Team Sports               155
Water Sports              147
Games                      86
Indoor Games               84
Gymnastics                 80
Winter Sports              75
Outdoor Play Equipment     63
Jumping                    60
Combat Sports              49
Racquet Sports             44
Air Sports                 36
Puzzles                    15
Dancing                    12
Name: category, dtype: int64

In [42]:
#Category full deatils
d=df.groupby('category')['category'].count().sort_values(ascending=False).head(1)
d1=df.loc[df['category']=='Outdoor Recreation']
d1

,oid,dat,cuid,pay_amount,category,product,city,state,method
5,5,02-14-2011,4007591,193.63,Outdoor Recreation,Camping & Backpacking & Hiking,Chicago,Illinois,credit
10,10,05-29-2011,4004646,180.28,Outdoor Recreation,Archery,Reno,Nevada,credit
31,29,06-03-2011,4005691,126.90,Outdoor Recreation,Hunting,Phoenix,Arizona,credit
35,33,06-15-2011,4005337,154.15,Outdoor Recreation,Lawn Games,Nashville,Tennessee,credit
39,37,04-19-2011,4005737,20.20,Outdoor Recreation,Shooting Games,San Diego,California,credit
...,...,...,...,...,...,...,...,...,...
1213,2194,06-22-2011,4002565,164.91,Outdoor Recreation,Archery,Irving,Texas,credit
1217,2198,02-19-2011,4004202,16.39,Outdoor Recreation,Lawn Games,Lexington,Kentucky,cash
1228,2209,07-06-2011,4003922,80.02,Outdoor Recreation,Motorsports,Huntsville,Alabama,credit
1231,2212,01-14-2011,4004614,167.39,Outdoor Recreation,Running,Boston,Massachusetts,credit
1239,2220,07-10-2011,4004649,130.40,Outdoor Recreation,Fishing,Springfield,Illinois,credit

In [43]:
#Each paymethod count
df3=df.groupby('method')['method'].count()
df3

method
cash       169
credit    1071
Name: method, dtype: int64

In [46]:
#jan-july month purchase count [include]

df5=df.loc[df['dat']<'09-01-2011']['oid'].count()
df5

np.int64(815)

In [47]:
#Each category total amount
df2=df.groupby('category')['pay_amount'].sum()
df2

category
Air Sports                 3213.27
Combat Sports              5423.44
Dancing                    1270.35
Exercise & Fitness        15898.60
Games                      8418.05
Gymnastics                 8610.72
Indoor Games               7832.52
Jumping                    6186.19
Outdoor Play Equipment     6448.90
Outdoor Recreation        18672.70
Puzzles                    1049.68
Racquet Sports             4632.47
Team Sports               16169.06
Water Sports              15246.15
Winter Sports              7160.43
Name: pay_amount, dtype: float64

In [48]:
#Each category maximum amount
df2=df.groupby('category')['pay_amount'].max()
df2

category
Air Sports                184.37
Combat Sports             198.36
Dancing                   188.59
Exercise & Fitness        199.15
Games                     192.68
Gymnastics                199.20
Indoor Games              190.26
Jumping                   199.19
Outdoor Play Equipment    198.85
Outdoor Recreation        198.20
Puzzles                   199.17
Racquet Sports            194.89
Team Sports               199.17
Water Sports              199.07
Winter Sports             198.83
Name: pay_amount, dtype: float64

In [49]:
#Each category avg amount
df2=df.groupby('category')['pay_amount'].mean()
df2

category
Air Sports                 89.257500
Combat Sports             110.682449
Dancing                   105.862500
Exercise & Fitness        101.914103
Games                      97.884302
Gymnastics                107.634000
Indoor Games               93.244286
Jumping                   103.103167
Outdoor Play Equipment    102.363492
Outdoor Recreation        104.902809
Puzzles                    69.978667
Racquet Sports            105.283409
Team Sports               104.316516
Water Sports              103.715306
Winter Sports              95.472400
Name: pay_amount, dtype: float64

In [51]:
#.total amount by cash and credit card
df5=df.groupby('method')['pay_amount'].sum()
df5

method
cash        4820.30
credit    121412.23
Name: pay_amount, dtype: float64

In [52]:
# Indoor games ,total amount
df6=df.loc[df['category']=='Indoor Games']['pay_amount'].sum()
df6

np.float64(7832.520000000001)

In [53]:
#Each state count
df7=df.groupby('state')['state'].count()
df7

state
Alabama                  33
Arizona                  36
California              181
Colorado                 42
Connecticut               9
District of Columbia      8
Florida                  76
Georgia                  17
Hawaii                   15
Idaho                     8
Illinois                 33
Indiana                  13
Iowa                     13
Kansas                   19
Kentucky                 21
Louisiana                 8
Maryland                 11
Massachusetts            27
Michigan                 25
Minnesota                21
Mississippi              10
Missouri                 31
Nebraska                 21
Nevada                   34
New Jersey               30
New York                 27
North Carolina           20
Ohio                     42
Oklahoma                  8
Oregon                   44
Pennsylvania             30
South Carolina           17
Tennessee                46
Texas                   141
Utah                     17
Virginia                 29
Washington               48
Wisconsin                29
Name: state, dtype: int64