In [10]:
import pandas as pd
import numpy as np
df=pd.read_csv(r'/content/customer1.csv')
df.isna().sum()

FileNotFoundError: [Errno 2] No such file or directory: '/content/customer1.csv'

In [ ]:
df.dropna(inplace=True)
df

In [11]:
df.isna().sum()

NameError: name 'df' is not defined

In [ ]:
df1=df.sort_values(by='age',ascending=False).head(5)[['fname','lname','age','prof']]
df1

In [ ]:
df1=df.sort_values(by='age').head(3)
df1=df1.drop('id',axis=1)
df1

In [ ]:
df9=df.loc[df['age']>50][['fname','lname','age']]
df9

In [ ]:
df11=df.loc[df['age']<30][['fname','lname','age','prof']]
df11

In [ ]:
df10=df.loc[df['loc']=='india'][['fname','lname']]
df10

In [ ]:
df10=df.loc[(df['loc']=='india')&(df['age']<30)][['fname','lname']]
df10

In [ ]:
#10.uk work and prof doctor fname , lname , age
df2=df.loc[(df['loc']=='uk')&(df['prof']=='Doctor')][['fname','lname','age']]
df2
#13.pilot prof , age max 1 , fname , lname, age, loc
df3=df.loc[(df['prof']=='Pilot')][['fname','lname','age','loc']]
df3.sort_values(by='age',ascending=False).head(1)
#14.pilot prof ,age min 1 , fname , lname age
df4=df.loc[df['prof']=='Pilot'][['fname','lname','age']].sort_values(by='age').head(1)
df4
#15.uk work age mini 10 emp fname , lname , prof
df1=df.sort_values(by='age').loc[df['loc']=='uk'][['fname','lname','prof']].head(10)
df1

In [ ]:
df111=df.drop(columns=['id','loc'])
df111

In [ ]:
dff=df[['fname','lname']]
dff

In [ ]:
df.values_count()

In [ ]:
df

In [ ]:
import pandas as pd
import numpy as np
df=pd.read_csv(r"/content/customer1.csv")

In [ ]:
import numpy as np
import pandas as pd
df=pd.read_csv(r"/content/customer1.csv")

In [12]:
import pandas as pd
import numpy as np
df=pd.read_csv(r'/content/customer1.csv')

FileNotFoundError: [Errno 2] No such file or directory: '/content/customer1.csv'

In [13]:
import pandas as pd
import numpy as np
df=pd.read_csv(r'/customer1.csv')

In [18]:
df1=df.loc[(df['age']>40) & (df['loc']=='india')].groupby('prof')['prof'].count().sort_values(ascending=False)

In [16]:
df1

prof
Carpenter                      3
Musician                       3
Childcare worker               1
Accountant                     1
Computer support specialist    1
Doctor                         1
Engineering technician         1
Financial analyst              1
Pharmacist                     1
Pilot                          1
Therapist                      1
Writer                         1
Name: prof, dtype: int64

In [19]:
df.value_counts('prof')

prof
Childcare worker                   17
Photographer                       15
Musician                           15
Loan officer                       14
Pilot                              13
Doctor                             13
Veterinarian                       13
Computer support specialist        12
Actor                              12
Statistician                       11
Civil engineer                     11
Electrical engineer                11
Politician                         11
Carpenter                          10
Economist                          10
Social worker                      10
Human resources assistant          10
Environmental scientist            10
Lawyer                             10
Athlete                             9
Coach                               9
Accountant                          9
Agricultural and food scientist     9
Nurse                               9
Firefighter                         9
Dancer                              9
Designer                            9
Recreation and fitness worker       9
Engineering technician              9
Therapist                           8
Secretary                           8
Architect                           8
Artist                              8
Librarian                           8
Pharmacist                          8
Farmer                              8
Electrician                         8
Reporter                            8
Physicist                           8
Police officer                      7
Computer software engineer          7
Computer hardware engineer          7
Chemist                             6
Automotive mechanic                 6
Judge                               6
Real estate agent                   6
Psychologist                        5
Writer                              5
Teacher                             5
Financial analyst                   4
africa                              1
Name: count, dtype: int64

In [21]:
#each prof max age
df2=df.groupby('prof')['age'].max().sort_values(ascending=False)
df2

prof
Artist                             75
Social worker                      75
Dancer                             74
Lawyer                             74
Physicist                          74
Politician                         74
Photographer                       74
Environmental scientist            74
Teacher                            74
Secretary                          74
Pilot                              74
Electrical engineer                74
Farmer                             74
Computer software engineer         73
Doctor                             73
Recreation and fitness worker      73
Economist                          73
Computer hardware engineer         73
Actor                              73
Psychologist                       73
Musician                           73
Firefighter                        73
Engineering technician             73
Nurse                              73
Veterinarian                       72
Librarian                          72
Financial analyst                  72
Loan officer                       72
Childcare worker                   72
Civil engineer                     72
Computer support specialist        72
Real estate agent                  71
Agricultural and food scientist    70
Automotive mechanic                70
Designer                           70
Reporter                           70
Chemist                            70
Statistician                       70
Pharmacist                         70
Athlete                            69
Therapist                          68
Electrician                        67
Judge                              67
Police officer                     67
Carpenter                          66
Architect                          66
Accountant                         64
Coach                              64
Human resources assistant          63
Writer                             60
africa                             58
Name: age, dtype: int64

In [22]:
df.isna().sum()

id       0
fname    0
lname    0
age      0
prof     0
loc      1
dtype: int64

In [25]:
df.fillna('africa',inplace=True)

In [26]:
df3=df.groupby('prof')['age'].min()

In [27]:
df3

prof
Accountant                         36
Actor                              35
Agricultural and food scientist    28
Architect                          21
Artist                             39
Athlete                            33
Automotive mechanic                30
Carpenter                          23
Chemist                            32
Childcare worker                   26
Civil engineer                     21
Coach                              21
Computer hardware engineer         22
Computer software engineer         38
Computer support specialist        25
Dancer                             28
Designer                           34
Doctor                             22
Economist                          22
Electrical engineer                27
Electrician                        22
Engineering technician             24
Environmental scientist            27
Farmer                             29
Financial analyst                  36
Firefighter                        22
Human resources assistant          23
Judge                              24
Lawyer                             26
Librarian                          28
Loan officer                       28
Musician                           23
Nurse                              21
Pharmacist                         30
Photographer                       32
Physicist                          24
Pilot                              25
Police officer                     28
Politician                         26
Psychologist                       25
Real estate agent                  32
Recreation and fitness worker      24
Reporter                           21
Secretary                          27
Social worker                      21
Statistician                       32
Teacher                            26
Therapist                          26
Veterinarian                       25
Writer                             26
africa                             58
Name: age, dtype: int64

In [28]:
#age
df4=df.groupby('prof')['age'].sum()

In [29]:
df4

prof
Accountant                         494
Actor                              696
Agricultural and food scientist    416
Architect                          356
Artist                             404
Athlete                            461
Automotive mechanic                282
Carpenter                          497
Chemist                            311
Childcare worker                   874
Civil engineer                     613
Coach                              377
Computer hardware engineer         370
Computer software engineer         407
Computer support specialist        566
Dancer                             455
Designer                           450
Doctor                             670
Economist                          471
Electrical engineer                554
Electrician                        392
Engineering technician             464
Environmental scientist            485
Farmer                             417
Financial analyst                  214
Firefighter                        422
Human resources assistant          458
Judge                              288
Lawyer                             448
Librarian                          352
Loan officer                       689
Musician                           747
Nurse                              447
Pharmacist                         410
Photographer                       831
Physicist                          350
Pilot                              671
Police officer                     327
Politician                         532
Psychologist                       251
Real estate agent                  267
Recreation and fitness worker      404
Reporter                           363
Secretary                          401
Social worker                      559
Statistician                       551
Teacher                            217
Therapist                          420
Veterinarian                       617
Writer                             223
africa                              58
Name: age, dtype: int64

In [30]:
#mean
df4=df.groupby('prof')['age'].mean()
df4

prof
Accountant                         54.888889
Actor                              58.000000
Agricultural and food scientist    46.222222
Architect                          44.500000
Artist                             50.500000
Athlete                            51.222222
Automotive mechanic                47.000000
Carpenter                          49.700000
Chemist                            51.833333
Childcare worker                   51.411765
Civil engineer                     55.727273
Coach                              41.888889
Computer hardware engineer         52.857143
Computer software engineer         58.142857
Computer support specialist        47.166667
Dancer                             50.555556
Designer                           50.000000
Doctor                             51.538462
Economist                          47.100000
Electrical engineer                50.363636
Electrician                        49.000000
Engineering technician             51.555556
Environmental scientist            48.500000
Farmer                             52.125000
Financial analyst                  53.500000
Firefighter                        46.888889
Human resources assistant          45.800000
Judge                              48.000000
Lawyer                             44.800000
Librarian                          44.000000
Loan officer                       49.214286
Musician                           49.800000
Nurse                              49.666667
Pharmacist                         51.250000
Photographer                       55.400000
Physicist                          43.750000
Pilot                              51.615385
Police officer                     46.714286
Politician                         48.363636
Psychologist                       50.200000
Real estate agent                  44.500000
Recreation and fitness worker      44.888889
Reporter                           45.375000
Secretary                          50.125000
Social worker                      55.900000
Statistician                       50.090909
Teacher                            43.400000
Therapist                          52.500000
Veterinarian                       47.461538
Writer                             44.600000
africa                             58.000000
Name: age, dtype: float64

In [31]:
dff=pd.read_csv(r'/customer5.csv')

In [41]:
##each prof count(desc)
df1=dff.groupby('prof')['prof'].count()
#df1
#each prof max salary
df2=dff.groupby('prof')['salary'].max()
#df2
#loc min salary(sal desc)
df3=dff.groupby('loc')['salary'].min().sort_values(ascending=False)
#df3
#each prof total salary
df4=dff.groupby('prof')['salary'].sum()
#df4
#each loc avg age
df5=dff.groupby('loc')['age'].mean()
df5
#each prof max age
#df6=dff.groupby('prof')['age'].max()
#df6

loc
africa       74.000000
australia    42.000000
china        66.000000
india        50.095238
ireland      43.000000
uk           45.540541
us           52.000000
Name: age, dtype: float64