In [17]:
import pandas as pd
import numpy as np

In [18]:
data={'colour':['red','green','blue','red','green'],
      'size':['small','medium','large','small','medium'],
      'material':['wood','wood','metal','wood','wood']}

In [19]:
df=pd.DataFrame(data)
df

  colour    size material
0    red   small     wood
1  green  medium     wood
2   blue   large    metal
3    red   small     wood
4  green  medium     wood

In [20]:
df.columns=['Colour','Size','Material']

In [21]:
df

  Colour    Size Material
0    red   small     wood
1  green  medium     wood
2   blue   large    metal
3    red   small     wood
4  green  medium     wood

In [22]:
df1=df.copy()

In [23]:
df1['Colour']=df1['Colour'].map({'red':0,'green':1,'blue':2})
df1['Material']=df1['Material'].map({'wood':0,'metal':1})
df1['Size']=df1['Size'].map({'small':0,'medium':1,'large':2})
df1

   Colour  Size  Material
0       0     0         0
1       1     1         0
2       2     2         1
3       0     0         0
4       1     1         0

In [24]:
df2=df.copy()

In [25]:
from sklearn.preprocessing import LabelEncoder
encode_c=LabelEncoder()
encode_m=LabelEncoder()
encode_s=LabelEncoder()

df2['Colour']=encode_c.fit_transform(df2['Colour'])
df2['Material']=encode_m.fit_transform(df2['Material'])
df2['Size']=encode_s.fit_transform(df2['Size'])
df2

   Colour  Size  Material
0       2     2         1
1       1     1         1
2       0     0         0
3       2     2         1
4       1     1         1

In [26]:
df2['Colour']=encode_c.inverse_transform(df2['Colour'])
df2['Material']=encode_m.inverse_transform(df2['Material'])
df2['Size']=encode_s.inverse_transform(df2['Size'])
df2

  Colour    Size Material
0    red   small     wood
1  green  medium     wood
2   blue   large    metal
3    red   small     wood
4  green  medium     wood

In [27]:
df3=df.copy()
cat_col=['Colour','Size','Material']
encoders=[LabelEncoder() for i in cat_col]

In [28]:
for i,col in enumerate(cat_col):
  df3[col]=encoders[i].fit_transform(df3[col])
df3

   Colour  Size  Material
0       2     2         1
1       1     1         1
2       0     0         0
3       2     2         1
4       1     1         1

In [29]:
for i,col in enumerate(cat_col):
  df3[col]=encoders[i].inverse_transform(df3[col])
df3

  Colour    Size Material
0    red   small     wood
1  green  medium     wood
2   blue   large    metal
3    red   small     wood
4  green  medium     wood

In [30]:
df4=df.copy()
pd.get_dummies(df4,dtype=int)

,Colour_blue,Colour_green,Colour_red,Size_large,Size_medium,Size_small,Material_metal,Material_wood
0,0,0,1,0,0,1,0,1
1,0,1,0,0,1,0,0,1
2,1,0,0,1,0,0,1,0
3,0,0,1,0,0,1,0,1
4,0,1,0,0,1,0,0,1

In [31]:
from sklearn.preprocessing import OneHotEncoder
encode1=OneHotEncoder()

In [32]:
df4=encode1.fit_transform(df4)
res=pd.DataFrame(df4.toarray())
res

     0    1    2    3    4    5    6    7
0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  1.0
1  0.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0
2  1.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0
3  0.0  0.0  1.0  0.0  0.0  1.0  0.0  1.0
4  0.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0