In [ ]:
import numpy as np
import pandas as pd
df=pd.read_csv(r'/content/glass_knn_numeric.csv')

In [ ]:
df

         RI     Na    Mg    Al     Si     K     Ca    Ba    Fe  Type
0    1.5121   11.1  1.14  1.79  72.57  2.96   6.59   low  0.23     5
1       NaN   13.4  3.61  1.15  69.39  0.46  11.21  0.09  0.16     3
2    1.5129    NaN  3.55  3.42  71.72  1.25  10.55   2.4  0.02     6
3    1.5111  15.22  0.31   1.4  72.80  1.06   6.98  1.09  0.07     2
4    1.5117  11.58  3.02   2.7  73.90  3.61  14.47  1.74  0.26     2
..      ...    ...   ...   ...    ...   ...    ...   ...   ...   ...
115  1.5103    NaN  3.17  3.44    NaN  4.97   8.91  0.87  0.12     2
116  1.5105   15.6  2.72   0.4  71.23  0.76  12.71  1.41  0.13     5
117     NaN  11.22   1.0   3.2  73.98  5.38  15.32   NaN  0.34     7
118  1.5236  16.92  3.47  2.33  70.01   NaN  12.65   1.3  0.22     1
119  1.5277  10.92  3.72  0.77  73.48  3.68  12.62   1.2  0.07     1

[120 rows x 10 columns]

In [ ]:
df.isna().sum()

RI      12
Na      12
Mg      12
Al      12
Si      12
K       12
Ca      12
Ba      12
Fe      12
Type     0
dtype: int64

In [ ]:
x=df.columns
for i in x:
  print(i,df[i].unique())

RI [1.5121    nan 1.5129 1.5111 1.5117 1.5261 1.5184 1.5298 1.5286 1.5128
 1.5239 1.5237 1.5224 1.529  1.5299 1.5183 1.5233 1.5282 1.5207 1.519
 1.5281 1.5156 1.5234 1.5113 1.5275 1.525  1.5163 1.5215 1.5134 1.512
 1.5153 1.5242 1.5208 1.5279 1.5217 1.5101 1.5118 1.5123 1.5289 1.5126
 1.5238 1.5169 1.5258 1.517  1.5108 1.514  1.5147 1.5165 1.5179 1.5276
 1.5154 1.516  1.5212 1.5104 1.5285 1.5127 1.5182 1.5198 1.5277 1.5225
 1.5251 1.5245 1.5216 1.5218 1.5158 1.5205 1.5133 1.5292 1.5287 1.524
 1.5267 1.5142 1.5294 1.51   1.5171 1.5223 1.5293 1.518  1.5186 1.5125
 1.526  1.5103 1.5105 1.5236]
Na ['11.1' '13.4' nan '15.22' '11.58' '11.82' '15.41' '14.1' '11.68' '16.15'
 '16.04' '15.27' '16.79' '11.37' '16.43' '16.34' '10.14' '16.48' '12.41'
 '10.13' '16.77' '11.84' '14.34' '13.93' '11.63' '13.43' '10.1' '16.64'
 '14.32' '10.42' '10.15' '14.68' '13.22' '10.5' '12.66' '13.04' '11.95'
 '11.42' '10.75' '16.47' '13.92' '15.79' '13.77' '12.76' '13.67' '15.93'
 '15.21' '15.65' '11.35' '11.77' '12.0' '15.89' '15.8' '15.15' '14.48'
 '14.49' '14.99' '15.23' '11.23' '10.87' '11.72' '12.72' '14.15' '13.87'
 '11.64' '13.82' '10.95' '13.86' '12.22' '16.65' '10.49' '13.9' '11.47'
 '10.11' '10.88' '10.46' '14.24' '12.32' '11.85' '16.52' '13.98' '15.59'
 '12.59' '10.47' '16.58' '14.07' '10.09' '14.19' '10.18' '14.06' '10.96'
 '10.2' '15.67' '13.85' '15.91' '16.35' '14.23' '16.41' 'fifteen' '15.6'
 '11.22' '16.92' '10.92']
Mg ['1.14' '3.61' '3.55' '0.31' '3.02' '0.72' '0.5' '0.0' '3.96' '2.75'
 '1.29' '3.1' '4.4' '0.89' '2.94' '3.38' '0.16' '1.42' '2.45' '0.44' '2.1'
 '3.85' '1.43' '4.12' '2.98' '1.69' '3.73' '2.85' '3.28' '3.93' '3.89'
 '1.12' '3.4' nan '1.7' '1.81' '3.52' '4.13' '1.94' '1.45' '1.41' '3.8'
 '2.15' 'missing' '3.59' '3.3' '2.59' '4.38' '1.16' '1.89' '1.22' '0.46'
 '2.03' '2.64' '0.1' '3.9' '3.06' '0.83' '2.83' '1.55' '2.01' '0.24'
 '0.94' '3.29' '3.53' '1.54' '2.34' '1.87' '2.37' '2.78' '3.94' '3.58'
 '3.83' '4.07' '4.42' '2.58' '4.27' '0.36' '2.25' '2.8' '1.17' '0.82'
 '2.56' '2.93' '1.92' '1.85' '4.02' '3.86' '2.6' '3.14' '3.84' '2.42'
 '3.6' '0.87' '1.05' '4.46' '3.65' '4.09' '3.17' '2.72' '1.0' '3.47'
 '3.72']
Al ['1.79' '1.15' '3.42' '1.4' '2.7' '1.77' '1.82' nan '3.37' '??' '0.36'
 '0.38' '1.52' '0.8' '2.29' '1.31' '1.26' '0.77' '2.92' '3.33' '2.86'
 '1.75' '0.81' '3.3' '3.19' '1.58' '1.09' '2.78' '3.47' '3.21' '3.01'
 '0.98' '2.53' '0.39' '0.73' '1.14' '2.69' '0.48' '1.1' '3.2' '2.34' '0.9'
 '1.56' '2.03' '1.67' '3.0' '3.06' '2.2' '1.94' '2.05' '2.57' '1.83'
 '2.72' '1.76' '2.64' '0.68' '2.52' '3.15' '3.48' '0.42' '1.47' '2.58'
 '2.75' '0.65' '2.28' '1.01' '0.33' '0.55' '2.59' '0.7' '2.87' '2.94'
 '0.56' '1.59' '1.25' '1.69' '2.3' '0.51' '1.29' '1.93' '0.4' '0.76'
 '2.16' '3.18' '0.95' '0.85' '3.23' '2.01' '2.85' '2.02' '1.97' '1.74'
 '3.44' '2.33']
Si [72.57 69.39 71.72 72.8  73.9  69.83 71.78   nan 71.12 74.52 74.5  72.11
 69.03 74.16 73.6  70.96 72.87 73.64 69.07 69.19 74.86 71.56 74.59 70.28
 72.03 72.36 72.64 73.62 70.89 70.64 73.01 70.85 72.45 69.16 71.48 70.32
 73.21 73.03 73.12 72.77 71.91 74.91 74.98 71.25 71.98 73.55 72.98 69.06
 74.41 73.53 70.92 69.08 70.11 72.47 74.13 72.46 70.48 73.14 74.07 72.42
 71.26 70.74 73.04 73.4  73.95 74.85 69.14 69.56 73.38 69.86 69.78 72.89
 71.71 70.17 71.86 70.88 69.34 73.47 71.74 71.57 70.05 70.44 70.19 74.84
 70.36 72.35 71.11 74.49 69.75 71.7  73.86 69.67 69.52 71.95 72.14 71.23
 73.98 70.01 73.48]
K ['2.96' '0.46' '1.25' '1.06' '3.61' '1.3' '4.55' '2.61' '0.48' nan '2.59'
 '0.9' '5.54' '5.01' '4.18' '4.65' '4.05' '2.41' '2.74' '4.56' '0.79'
 '5.16' '2.22' '4.24' '5.86' '5.26' '1.67' '5.3' '4.53' '1.13' '1.81'
 '1.33' '1.77' '0.64' '3.94' '2.55' '1.26' '0.12' '3.83' '3.26' '4.62'
 '5.5' '0.02' '5.17' '1.8' '0.34' '0.96' '4.34' '4.69' '3.76' '3.32'
 '3.18' '2.42' '4.68' 'none' '2.43' '1.32' '0.83' '1.83' '2.87' '2.25'
 '1.39' '2.37' '2.8' '0.72' '5.91' '2.14' '4.37' '1.24' '3.1' '4.44'
 '4.71' '1.44' '5.43' '4.72' '3.05' '1.74' '0.27' '5.92' '5.67' '1.89'
 '1.14' '3.31' '2.66' '1.15' '3.58' '2.69' '4.8' '4.73' '4.38' '1.94'
 '1.72' '3.68' '2.07' '4.3' '4.5' '0.88' '3.35' '4.97' '0.76' '5.38']
Ca [ 6.59 11.21 10.55  6.98 14.47 12.   12.67 10.7   7.09   nan 14.22  8.52
  7.14  9.6   9.58 12.78 12.51  9.67  9.13  5.16  6.48  8.24 14.33 10.94
 10.66  8.25  5.1  10.37  8.54  8.76 11.75 10.26  9.47  9.72 15.37 14.86
 14.05 13.72  7.81 12.88 15.14 10.48  5.15  7.77 10.58 15.44 14.43 10.41
  6.64  5.75  6.14  8.63 11.82 14.88  9.84  5.09  6.92 12.57 11.31  9.91
 13.43 11.87  9.38 10.09 14.27 10.99 12.13 13.58 13.71 14.77  7.03  7.02
 14.41  8.77 15.61  9.5  13.74  7.79  6.9  15.21  6.87  7.66 15.81  9.09
 12.52 13.83 15.    5.85 11.66 15.41  7.5  12.69 11.7  11.95  8.07 11.44
 15.88  9.48  8.93  8.91 12.71 15.32 12.65 12.62]
Ba ['low' '0.09' '2.4' '1.09' '1.74' '1.67' '2.94' '2.58' '1.14' '0.65'
 '0.46' '0.13' '2.01' '0.85' '0.81' '1.25' '1.2' '0.48' '1.23' '0.58'
 '1.13' '1.46' '0.6' '1.71' '2.24' '1.9' '2.96' nan '2.13' '2.02' '2.55'
 '1.48' '1.28' '0.33' '2.32' '0.16' '1.41' '0.96' '0.89' '0.32' '2.25'
 '1.5' '1.35' '0.22' '1.55' '1.05' '0.14' '2.99' '0.44' '1.02' '1.89'
 '0.18' '2.18' '2.77' '1.92' '2.9' '0.43' '1.53' '0.37' '1.43' '2.53'
 '1.94' '1.21' '1.82' '2.33' '1.98' '1.51' '0.69' '0.45' '1.58' '1.11'
 '2.73' '1.96' '1.59' '0.87' '0.56' '2.67' '1.93' '1.66' '1.36' '1.27'
 '1.06' '2.97' '0.34' '1.03' '1.15' '0.79' '1.8' '2.39' '0.05' '2.62'
 '2.66' '1.7' '0.74' '0.54' '1.3']
Fe ['0.23' '0.16' '0.02' '0.07' '0.26' nan '0.27' '0.15' '0.11' '0.22' '0.45'
 '0.47' '0.21' '0.5' '0.31' '0.01' '0.14' '0.38' '0.44' '0.24' '0.37'
 '0.19' '0.39' '0.1' '0.03' '0.41' '0.17' '0.29' '0.48' '0.13' '0.04'
 '0.12' '0.35' '0.49' '0.33' '0.34' '0.46' '0.06' '0.3' '0.42' 'zero'
 '0.05' '0.43']
Type [5 3 6 2 7 1]

In [ ]:
df['Na']=df['Na'].replace('fifteen',15)
df['Mg']=df['Mg'].replace('missing',np.nan)
df['Al']=df['Al'].replace('??',np.nan)
df['K']=df['K'].replace('none',np.nan)
df['Ba']=df['Ba'].replace('low',np.nan)
df['Fe']=df['Fe'].replace('zero',np.nan)

In [ ]:
for i in x:
  df[i]=df[i].astype(float)
  df[i]=df[i].fillna(df[i].mean())

In [ ]:
df.isna().sum()

RI      0
Na      0
Mg      0
Al      0
Si      0
K       0
Ca      0
Ba      0
Fe      0
Type    0
dtype: int64

In [ ]:
df['Al']

0      1.79
1      1.15
2      3.42
3      1.40
4      2.70
       ...
115    3.44
116    0.40
117    3.20
118    2.33
119    0.77
Name: Al, Length: 120, dtype: float64

In [ ]:
x=df.drop('Type',axis=1)
x.ndim
y=df['Type']
y.ndim

1

In [ ]:
from sklearn.model_selection import train_test_split
x_tr,x_te,y_tr,y_te=train_test_split(x,y,test_size=0.30,random_state=42)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
sc.fit(x_tr)
x_tr=sc.transform(x_tr)
x_te=sc.transform(x_te)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
knn.fit(x_tr,y_tr)
y_pred=knn.predict(x_te)

In [ ]:
y_pred

array([7., 1., 6., 1., 2., 2., 1., 1., 2., 6., 5., 3., 2., 6., 1., 2., 6.,
       6., 6., 1., 2., 6., 1., 5., 2., 2., 2., 6., 6., 2., 1., 1., 2., 5.,
       1., 5.])

In [ ]:
y_te.values

array([7., 3., 5., 5., 7., 2., 2., 6., 6., 5., 2., 2., 2., 1., 5., 2., 5.,
       1., 2., 3., 3., 5., 3., 5., 2., 3., 7., 7., 2., 1., 7., 6., 7., 3.,
       7., 6.])

In [ ]:
df

,RI,Na,Mg,Al,Si,K,Ca,Ba,Fe,Type
0,1.512100,11.100000,1.14,1.79,72.570000,2.960000,6.59,1.403738,0.23,5.0
1,1.520141,13.400000,3.61,1.15,69.390000,0.460000,11.21,0.090000,0.16,3.0
2,1.512900,13.441389,3.55,3.42,71.720000,1.250000,10.55,2.400000,0.02,6.0
3,1.511100,15.220000,0.31,1.40,72.800000,1.060000,6.98,1.090000,0.07,2.0
4,1.511700,11.580000,3.02,2.70,73.900000,3.610000,14.47,1.740000,0.26,2.0
...,...,...,...,...,...,...,...,...,...,...
115,1.510300,13.441389,3.17,3.44,71.959537,4.970000,8.91,0.870000,0.12,2.0
116,1.510500,15.600000,2.72,0.40,71.230000,0.760000,12.71,1.410000,0.13,5.0
117,1.520141,11.220000,1.00,3.20,73.980000,5.380000,15.32,1.403738,0.34,7.0
118,1.523600,16.920000,3.47,2.33,70.010000,2.908785,12.65,1.300000,0.22,1.0
119,1.527700,10.920000,3.72,0.77,73.480000,3.680000,12.62,1.200000,0.07,1.0

In [ ]:
knn.predict(sc.transform([[1.511100,15.220000,0.31,1.40,72.800000,1.060000,6.98,1.090000,0.07]]))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

array([2.])

In [ ]:
from sklearn.matrix