In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv(r'/content/heart.csv')
df.isna().sum()

age         0
sex         0
cp          0
trestbps    1
chol        0
fbs         0
restecg     1
thalach     1
exang       0
oldpeak     0
slope       0
ca          2
thal        1
target      0
dtype: int64

In [2]:
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125.0,212,0,NaN,168.0,0,1.0,2,2.0,3.0,0
1,53,1,0,140.0,203,1,0.0,155.0,1,3.1,0,0.0,3.0,0
2,70,1,0,145.0,174,0,1.0,125.0,1,2.6,0,0.0,3.0,0
3,61,1,0,148.0,203,0,1.0,NaN,0,0.0,2,1.0,3.0,0
4,62,0,0,138.0,294,1,1.0,106.0,0,1.9,1,3.0,2.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140.0,221,0,1.0,164.0,1,0.0,2,0.0,2.0,1
1021,60,1,0,125.0,258,0,0.0,141.0,1,2.8,1,1.0,3.0,0
1022,47,1,0,110.0,275,0,0.0,118.0,1,1.0,1,1.0,2.0,0
1023,50,0,0,110.0,254,0,0.0,159.0,0,0.0,2,0.0,2.0,1
1024,54,1,0,120.0,188,0,1.0,113.0,0,1.4,1,1.0,3.0,0

In [3]:
df['ca']=df['ca'].fillna((df['ca'].mode())

In [4]:
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125.0,212,0,NaN,168.0,0,1.0,2,2.0,3.0,0
1,53,1,0,140.0,203,1,0.0,155.0,1,3.1,0,0.0,3.0,0
2,70,1,0,145.0,174,0,1.0,125.0,1,2.6,0,0.0,3.0,0
3,61,1,0,148.0,203,0,1.0,NaN,0,0.0,2,1.0,3.0,0
4,62,0,0,138.0,294,1,1.0,106.0,0,1.9,1,3.0,2.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140.0,221,0,1.0,164.0,1,0.0,2,0.0,2.0,1
1021,60,1,0,125.0,258,0,0.0,141.0,1,2.8,1,1.0,3.0,0
1022,47,1,0,110.0,275,0,0.0,118.0,1,1.0,1,1.0,2.0,0
1023,50,0,0,110.0,254,0,0.0,159.0,0,0.0,2,0.0,2.0,1
1024,54,1,0,120.0,188,0,1.0,113.0,0,1.4,1,1.0,3.0,0

In [5]:
df.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,1025.000000,1025.000000,1025.000000,1024.000000,1025.00000,1025.000000,1024.000000,1024.000000,1025.000000,1025.000000,1025.000000,1025.000000,1024.000000,1025.000000
mean,54.434146,0.695610,0.942439,131.603516,246.00000,0.149268,0.529297,149.102539,0.336585,1.071512,1.385366,0.751220,2.324219,0.513171
std,9.072290,0.460373,1.029641,17.523313,51.59251,0.356527,0.527931,23.013962,0.472772,1.175053,0.617755,1.028671,0.620881,0.500070
min,29.000000,0.000000,0.000000,94.000000,126.00000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,48.000000,0.000000,0.000000,120.000000,211.00000,0.000000,0.000000,132.000000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,56.000000,1.000000,1.000000,130.000000,240.00000,0.000000,1.000000,152.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,275.00000,0.000000,1.000000,166.000000,1.000000,1.800000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.00000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [9]:
df['thal'].mode()[0]

np.float64(2.0)

In [10]:
df['thal']=df['thal'].fillna(df['thal'].mode()[0])

In [11]:
df.isna().sum()

age         0
sex         0
cp          0
trestbps    1
chol        0
fbs         0
restecg     1
thalach     1
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [12]:
df['trestbps']=df['trestbps'].fillna(df['trestbps'].mode()[0])

In [13]:
df['restecg']=df['restecg'].fillna(df['restecg'].mode()[0])

In [14]:
df['thalach']=df['thalach'].fillna(df['thalach'].mode()[0])

In [15]:
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125.0,212,0,1.0,168.0,0,1.0,2,2.0,3.0,0
1,53,1,0,140.0,203,1,0.0,155.0,1,3.1,0,0.0,3.0,0
2,70,1,0,145.0,174,0,1.0,125.0,1,2.6,0,0.0,3.0,0
3,61,1,0,148.0,203,0,1.0,162.0,0,0.0,2,1.0,3.0,0
4,62,0,0,138.0,294,1,1.0,106.0,0,1.9,1,3.0,2.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140.0,221,0,1.0,164.0,1,0.0,2,0.0,2.0,1
1021,60,1,0,125.0,258,0,0.0,141.0,1,2.8,1,1.0,3.0,0
1022,47,1,0,110.0,275,0,0.0,118.0,1,1.0,1,1.0,2.0,0
1023,50,0,0,110.0,254,0,0.0,159.0,0,0.0,2,0.0,2.0,1
1024,54,1,0,120.0,188,0,1.0,113.0,0,1.4,1,1.0,3.0,0

In [16]:
from numpy._core.defchararray import count
#each target column count ---> count in desc order
df1=df.groupby('target')['target'].count().sort_values(ascending=False)

In [18]:
df1

target
1    526
0    499
Name: target, dtype: int64

In [19]:
#each age group count -----> count in desc
df2=df.groupby('age')['age'].count().sort_values(ascending=False)
df2

age
58    68
57    57
54    53
59    46
52    43
51    39
56    39
60    37
62    37
44    36
64    34
41    32
63    32
61    31
67    31
55    30
65    27
53    26
43    26
42    26
66    25
45    25
46    23
48    23
50    21
47    18
49    17
35    15
70    14
39    14
38    12
68    12
40    11
71    11
69     9
37     6
34     6
29     4
74     3
76     3
77     3
Name: age, dtype: int64

In [22]:
#age above 50 , each heart patient count
df3=df.loc[(df['age']>50)&(df['target']==1)]
df3

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
5,58,0,0,100.0,248,0,0.0,122.0,0,1.0,1,0.0,2.0,1
10,71,0,0,112.0,149,0,1.0,125.0,0,1.6,1,0.0,2.0,1
16,51,0,2,120.0,308,0,0.0,142.0,0,1.5,2,1.0,2.0,1
19,58,1,2,140.0,211,1,0.0,165.0,0,0.0,2,0.0,2.0,1
21,67,0,0,106.0,223,0,1.0,142.0,0,0.3,2,2.0,2.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1003,52,1,0,108.0,233,1,1.0,147.0,0,0.1,2,3.0,3.0,1
1004,51,0,2,140.0,308,0,0.0,142.0,0,1.5,2,1.0,2.0,1
1006,58,1,2,140.0,211,1,0.0,165.0,0,0.0,2,0.0,2.0,1
1007,56,1,3,120.0,193,0,0.0,162.0,0,1.9,1,0.0,3.0,1
1020,59,1,1,140.0,221,0,1.0,164.0,1,0.0,2,0.0,2.0,1

In [34]:
#sep x and y (x---input columns ) and (y---output column)
x1=df.drop('target',axis=1)
x1

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,52,1,0,125.0,212,0,1.0,168.0,0,1.0,2,2.0,3.0
1,53,1,0,140.0,203,1,0.0,155.0,1,3.1,0,0.0,3.0
2,70,1,0,145.0,174,0,1.0,125.0,1,2.6,0,0.0,3.0
3,61,1,0,148.0,203,0,1.0,162.0,0,0.0,2,1.0,3.0
4,62,0,0,138.0,294,1,1.0,106.0,0,1.9,1,3.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140.0,221,0,1.0,164.0,1,0.0,2,0.0,2.0
1021,60,1,0,125.0,258,0,0.0,141.0,1,2.8,1,1.0,3.0
1022,47,1,0,110.0,275,0,0.0,118.0,1,1.0,1,1.0,2.0
1023,50,0,0,110.0,254,0,0.0,159.0,0,0.0,2,0.0,2.0
1024,54,1,0,120.0,188,0,1.0,113.0,0,1.4,1,1.0,3.0

In [48]:
y=df['target']
y

0       0.0
1       0.0
2       0.0
3       0.0
4       0.0
       ...
1020    1.0
1021    0.0
1022    0.0
1023    1.0
1024    0.0
Name: target, Length: 1025, dtype: float64

In [38]:
#talach above 180 is wrong data ----replace with mean
df['thalach'].mean()

np.float64(149.11512195121952)

In [50]:
df.loc[df['thalach']>180]=int(df['thalach'].mean())

In [42]:
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52.0,1.0,0.0,125.0,212.0,0.0,1.0,168.0,0.0,1.0,2.0,2.0,3.0,0.0
1,53.0,1.0,0.0,140.0,203.0,1.0,0.0,155.0,1.0,3.1,0.0,0.0,3.0,0.0
2,70.0,1.0,0.0,145.0,174.0,0.0,1.0,125.0,1.0,2.6,0.0,0.0,3.0,0.0
3,61.0,1.0,0.0,148.0,203.0,0.0,1.0,162.0,0.0,0.0,2.0,1.0,3.0,0.0
4,62.0,0.0,0.0,138.0,294.0,1.0,1.0,106.0,0.0,1.9,1.0,3.0,2.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59.0,1.0,1.0,140.0,221.0,0.0,1.0,164.0,1.0,0.0,2.0,0.0,2.0,1.0
1021,60.0,1.0,0.0,125.0,258.0,0.0,0.0,141.0,1.0,2.8,1.0,1.0,3.0,0.0
1022,47.0,1.0,0.0,110.0,275.0,0.0,0.0,118.0,1.0,1.0,1.0,1.0,2.0,0.0
1023,50.0,0.0,0.0,110.0,254.0,0.0,0.0,159.0,0.0,0.0,2.0,0.0,2.0,1.0
1024,54.0,1.0,0.0,120.0,188.0,0.0,1.0,113.0,0.0,1.4,1.0,1.0,3.0,0.0

In [52]:
d=df.groupby('thalach')['thalach'].count()
d

thalach
71.0      4
88.0      3
90.0      3
95.0      4
96.0      7
         ..
175.0    10
177.0     3
178.0    15
179.0    16
180.0     6
Name: thalach, Length: 80, dtype: int64