In [155]:
import pandas as pd
df_te=pd.read_csv(r'/content/drive/MyDrive/Datasets/SMS_test.csv',encoding='ISO-8859-1')
x_te=df_te.drop(columns=['S. No.','Label'])
y_te=df_te['Label']

In [156]:
df_tr=pd.read_csv(r'/content/drive/MyDrive/Datasets/SMS_train.csv',encoding='ISO-8859-1')
x_tr=df_tr.drop(columns=['S. No.','Label'])
y_tr=df_tr['Label']

In [157]:
y_te=y_te.map({'Spam':1,'Non-Spam':0})

In [158]:
y_tr=y_tr.map({'Spam':1,'Non-Spam':0})
y_tr

0      0
1      0
2      0
3      0
4      1
      ..
952    0
953    0
954    0
955    0
956    0
Name: Label, Length: 957, dtype: int64

In [159]:
x_tr

                                          Message_body
0                           Rofl. Its true to its name
1    The guy did some bitching but I acted like i'd...
2    Pity, * was in mood for that. So...any other s...
3                 Will ü b going to esplanade fr home?
4    This is the 2nd time we have tried 2 contact u...
..                                                 ...
952  hows my favourite person today? r u workin har...
953                      How much you got for cleaning
954  Sorry da. I gone mad so many pending works wha...
955                                 Wat time ü finish?
956                    Just glad to be talking to you.

[957 rows x 1 columns]

In [160]:
x_tr=x_tr['Message_body']
x_tr=x_tr.str.replace('[^A-z ]','',regex=True)
x_te=x_te['Message_body']
x_te=x_te.str.replace('[^A-z ]','',regex=True)

In [161]:
x_tr

0                              Rofl Its true to its name
1      The guy did some bitching but I acted like id ...
2      Pity  was in mood for that Soany other suggest...
3                     Will  b going to esplanade fr home
4      This is the nd time we have tried  contact u U...
                             ...
952    hows my favourite person today r u workin hard...
953                        How much you got for cleaning
954    Sorry da I gone mad so many pending works what...
955                                     Wat time  finish
956                       Just glad to be talking to you
Name: Message_body, Length: 957, dtype: object

In [162]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
w=stopwords.words('english')
from nltk.stem import SnowballStemmer
nltk.download('punkt_tab')
sbs=SnowballStemmer('english')
x_tr=x_tr.apply(lambda line:[sbs.stem(word) for word in nltk.word_tokenize(line) if len(word)>1 and word.lower() not in w]).apply(lambda s:' '.join(s))
x_te=x_te.apply(lambda line:[sbs.stem(word) for word in nltk.word_tokenize(line) if len(word)>1 and word.lower() not in w]).apply(lambda s:' '.join(s))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [163]:
x_tr

0                                         rofl true name
1      guy bitch act like id interest buy someth els ...
2                                piti mood soani suggest
3                                    go esplanad fr home
4      nd time tri contact pound prize claim easi cal...
                             ...
952    how favourit person today workin hard couldnt ...
953                                       much got clean
954                     sorri da gone mad mani pend work
955                                      wat time finish
956                                            glad talk
Name: Message_body, Length: 957, dtype: object

In [164]:
from sklearn.feature_extraction.text import TfidfVectorizer
vect=TfidfVectorizer()
tr=vect.fit_transform(x_tr)
te=vect.transform(x_te)

In [165]:
tr

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 7575 stored elements and shape (957, 2550)>

In [166]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB,BernoulliNB
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier
from sklearn.metrics import classification_report
models=[KNeighborsClassifier(),GaussianNB(),BernoulliNB(),RandomForestClassifier(random_state=11),AdaBoostClassifier(random_state=11)]
for obj in models:
  obj.fit(tr.toarray(),y_tr)
  y_pred=obj.predict(te.toarray())
  print(obj)
  print(classification_report(y_te,y_pred))

KNeighborsClassifier()
              precision    recall  f1-score   support

           0       0.42      1.00      0.59        49
           1       1.00      0.12      0.21        76

    accuracy                           0.46       125
   macro avg       0.71      0.56      0.40       125
weighted avg       0.77      0.46      0.36       125

GaussianNB()
              precision    recall  f1-score   support

           0       0.71      0.96      0.82        49
           1       0.97      0.75      0.84        76

    accuracy                           0.83       125
   macro avg       0.84      0.85      0.83       125
weighted avg       0.87      0.83      0.83       125

BernoulliNB()
              precision    recall  f1-score   support

           0       0.57      1.00      0.73        49
           1       1.00      0.51      0.68        76

    accuracy                           0.70       125
   macro avg       0.78      0.76      0.70       125
weighted avg       0.83      0.70      0.70       125

RandomForestClassifier(random_state=11)
              precision    recall  f1-score   support

           0       0.62      1.00      0.77        49
           1       1.00      0.61      0.75        76

    accuracy                           0.76       125
   macro avg       0.81      0.80      0.76       125
weighted avg       0.85      0.76      0.76       125

AdaBoostClassifier(random_state=11)
              precision    recall  f1-score   support

           0       0.58      0.98      0.73        49
           1       0.98      0.54      0.69        76

    accuracy                           0.71       125
   macro avg       0.78      0.76      0.71       125
weighted avg       0.82      0.71      0.71       125