In [2]:
import pandas as pd
import numpy as np
df=pd.read_csv(r'/content/online_store_sales_modified.csv')
df

,Order_ID,Customer_Name,Age,Gender,City,Product_Category,Product,Quantity,Price,Discount (%),Payment_Method,Order_Date
0,1001,Aisha,19.0,F,Chennai,Clothing,Jeans,1,44448,20.0,UPI,2025-02-07
1,1002,Isabella,20.0,M,Bengaluru,Clothing,Jeans,5,39553,0.0,Net Banking,2025-01-13
2,1003,Chloe,44.0,M,Ahmedabad,Books,Magazine,1,49829,5.0,Cash,2025-01-22
3,1004,Ravi,27.0,M,kochi,Electronics,Mobile,4,6438,10.0,Debit Card,2025-02-08
4,1005,Ravi,20.0,F,Bengaluru,Home Decor,Lamp,5,19313,20.0,Debit Card,2025-02-06
...,...,...,...,...,...,...,...,...,...,...,...,...
567,1541,Ethan,NaN,M,Hyderabad,Clothing,Jeans,2,35910,20.0,Debit Card,2025-02-05
568,1526,Sophia,NaN,M,Pune,Books,Magazine,3,29748,15.0,Cash,2025-01-01
569,1235,Kevin,NaN,F,Pune,Toys,Car,1,12431,20.0,Net Banking,2025-01-14
570,1527,Maria,NaN,M,Delhi,Grocery,Rice,3,14641,5.0,Debit Card,2025-01-02
571,1491,Emma,NaN,F,Mumbai,Home Decor,Cushion,5,34240,15.0,Cash,2025-01-11

In [3]:
df.isna().sum()

Order_ID             0
Customer_Name        0
Age                 10
Gender               0
City                 5
Product_Category     0
Product              0
Quantity             0
Price                0
Discount (%)         5
Payment_Method       5
Order_Date           0
dtype: int64

In [4]:
df['Age']=df['Age'].fillna(df['Age'].mode()[0])
df['City']=df['City'].fillna(df['City'].mode()[0])

In [5]:
df

,Order_ID,Customer_Name,Age,Gender,City,Product_Category,Product,Quantity,Price,Discount (%),Payment_Method,Order_Date
0,1001,Aisha,19.0,F,Chennai,Clothing,Jeans,1,44448,20.0,UPI,2025-02-07
1,1002,Isabella,20.0,M,Bengaluru,Clothing,Jeans,5,39553,0.0,Net Banking,2025-01-13
2,1003,Chloe,44.0,M,Ahmedabad,Books,Magazine,1,49829,5.0,Cash,2025-01-22
3,1004,Ravi,27.0,M,kochi,Electronics,Mobile,4,6438,10.0,Debit Card,2025-02-08
4,1005,Ravi,20.0,F,Bengaluru,Home Decor,Lamp,5,19313,20.0,Debit Card,2025-02-06
...,...,...,...,...,...,...,...,...,...,...,...,...
567,1541,Ethan,26.0,M,Hyderabad,Clothing,Jeans,2,35910,20.0,Debit Card,2025-02-05
568,1526,Sophia,26.0,M,Pune,Books,Magazine,3,29748,15.0,Cash,2025-01-01
569,1235,Kevin,26.0,F,Pune,Toys,Car,1,12431,20.0,Net Banking,2025-01-14
570,1527,Maria,26.0,M,Delhi,Grocery,Rice,3,14641,5.0,Debit Card,2025-01-02
571,1491,Emma,26.0,F,Mumbai,Home Decor,Cushion,5,34240,15.0,Cash,2025-01-11

In [6]:
df['Payment_Method']=df['Payment_Method'].fillna(df['Payment_Method'].ffill)

In [7]:
df=df.fillna(0)

In [8]:
df.isna().sum()

Order_ID            0
Customer_Name       0
Age                 0
Gender              0
City                0
Product_Category    0
Product             0
Quantity            0
Price               0
Discount (%)        0
Payment_Method      0
Order_Date          0
dtype: int64

In [9]:
df

,Order_ID,Customer_Name,Age,Gender,City,Product_Category,Product,Quantity,Price,Discount (%),Payment_Method,Order_Date
0,1001,Aisha,19.0,F,Chennai,Clothing,Jeans,1,44448,20.0,UPI,2025-02-07
1,1002,Isabella,20.0,M,Bengaluru,Clothing,Jeans,5,39553,0.0,Net Banking,2025-01-13
2,1003,Chloe,44.0,M,Ahmedabad,Books,Magazine,1,49829,5.0,Cash,2025-01-22
3,1004,Ravi,27.0,M,kochi,Electronics,Mobile,4,6438,10.0,Debit Card,2025-02-08
4,1005,Ravi,20.0,F,Bengaluru,Home Decor,Lamp,5,19313,20.0,Debit Card,2025-02-06
...,...,...,...,...,...,...,...,...,...,...,...,...
567,1541,Ethan,26.0,M,Hyderabad,Clothing,Jeans,2,35910,20.0,Debit Card,2025-02-05
568,1526,Sophia,26.0,M,Pune,Books,Magazine,3,29748,15.0,Cash,2025-01-01
569,1235,Kevin,26.0,F,Pune,Toys,Car,1,12431,20.0,Net Banking,2025-01-14
570,1527,Maria,26.0,M,Delhi,Grocery,Rice,3,14641,5.0,Debit Card,2025-01-02
571,1491,Emma,26.0,F,Mumbai,Home Decor,Cushion,5,34240,15.0,Cash,2025-01-11

In [10]:
df.describe(include='all')

,Order_ID,Customer_Name,Age,Gender,City,Product_Category,Product,Quantity,Price,Discount (%),Payment_Method,Order_Date
count,572.000000,572,572.000000,572,572,572,572,572.000000,572.000000,572.000000,572,572
unique,NaN,20,NaN,3,9,8,24,NaN,NaN,NaN,7,61
top,NaN,Sophia,NaN,F,Hyderabad,Books,Comics,NaN,NaN,NaN,Net Banking,2025-01-21
freq,NaN,39,NaN,291,87,126,39,NaN,NaN,NaN,123,17
mean,1285.573427,NaN,38.508741,NaN,NaN,NaN,NaN,3.022727,31237.993007,10.078671,NaN,NaN
std,164.321051,NaN,12.437371,NaN,NaN,NaN,NaN,1.390929,17118.178916,7.123069,NaN,NaN
min,1001.000000,NaN,18.000000,NaN,NaN,NaN,NaN,1.000000,171.000000,0.000000,NaN,NaN
25%,1143.750000,NaN,27.000000,NaN,NaN,NaN,NaN,2.000000,17312.750000,5.000000,NaN,NaN
50%,1285.500000,NaN,38.000000,NaN,NaN,NaN,NaN,3.000000,30277.500000,10.000000,NaN,NaN
75%,1428.250000,NaN,49.000000,NaN,NaN,NaN,NaN,4.000000,45828.250000,15.000000,NaN,NaN
max,1567.000000,NaN,60.000000,NaN,NaN,NaN,NaN,5.000000,59784.000000,20.000000,NaN,NaN

In [11]:
d=df.columns
for i in d:
  print(df[i].unique())

[1001 1002 1003 1004 1005 1006 1007 1008 1009 1010 1011 1012 1013 1014
 1015 1016 1017 1018 1019 1020 1021 1022 1023 1024 1025 1026 1027 1028
 1029 1030 1031 1032 1033 1034 1035 1036 1037 1038 1039 1040 1041 1042
 1043 1044 1045 1046 1047 1048 1049 1050 1051 1052 1053 1054 1055 1056
 1057 1058 1059 1060 1061 1062 1063 1064 1065 1066 1067 1068 1069 1070
 1071 1072 1073 1074 1075 1076 1077 1078 1079 1080 1081 1082 1083 1084
 1085 1086 1087 1088 1089 1090 1091 1092 1093 1094 1095 1096 1097 1098
 1099 1100 1101 1102 1103 1104 1105 1106 1107 1108 1109 1110 1111 1112
 1113 1114 1115 1116 1117 1118 1119 1120 1121 1122 1123 1124 1125 1126
 1127 1128 1129 1130 1131 1132 1133 1134 1135 1136 1137 1138 1139 1140
 1141 1142 1143 1144 1145 1146 1147 1148 1149 1150 1151 1152 1153 1154
 1155 1156 1157 1158 1159 1160 1161 1162 1163 1164 1165 1166 1167 1168
 1169 1170 1171 1172 1173 1174 1175 1176 1177 1178 1179 1180 1181 1182
 1183 1184 1185 1186 1187 1188 1189 1190 1191 1192 1193 1194 1195 1196
 1197 1198 1199 1200 1201 1202 1203 1204 1205 1206 1207 1208 1209 1210
 1211 1212 1213 1214 1215 1216 1217 1218 1219 1220 1221 1222 1223 1224
 1225 1226 1227 1228 1229 1230 1231 1232 1233 1234 1235 1236 1237 1238
 1239 1240 1241 1242 1243 1244 1245 1246 1247 1248 1249 1250 1251 1252
 1253 1254 1255 1256 1257 1258 1259 1260 1261 1262 1263 1264 1265 1266
 1267 1268 1269 1270 1271 1272 1273 1274 1275 1276 1277 1278 1279 1280
 1281 1282 1283 1284 1285 1286 1287 1288 1289 1290 1291 1292 1293 1294
 1295 1296 1297 1298 1299 1300 1301 1302 1303 1304 1305 1306 1307 1308
 1309 1310 1311 1312 1313 1314 1315 1316 1317 1318 1319 1320 1321 1322
 1323 1324 1325 1326 1327 1328 1329 1330 1331 1332 1333 1334 1335 1336
 1337 1338 1339 1340 1341 1342 1343 1344 1345 1346 1347 1348 1349 1350
 1351 1352 1353 1354 1355 1356 1357 1358 1359 1360 1361 1362 1363 1364
 1365 1366 1367 1368 1369 1370 1371 1372 1373 1374 1375 1376 1377 1378
 1379 1380 1381 1382 1383 1384 1385 1386 1387 1388 1389 1390 1391 1392
 1393 1394 1395 1396 1397 1398 1399 1400 1401 1402 1403 1404 1405 1406
 1407 1408 1409 1410 1411 1412 1413 1414 1415 1416 1417 1418 1419 1420
 1421 1422 1423 1424 1425 1426 1427 1428 1429 1430 1431 1432 1433 1434
 1435 1436 1437 1438 1439 1440 1441 1442 1443 1444 1445 1446 1447 1448
 1449 1450 1451 1452 1453 1454 1455 1456 1457 1458 1459 1460 1461 1462
 1463 1464 1465 1466 1467 1468 1469 1470 1471 1472 1473 1474 1475 1476
 1477 1478 1479 1480 1481 1482 1483 1484 1485 1486 1487 1488 1489 1490
 1491 1492 1493 1494 1495 1496 1497 1498 1499 1500 1501 1502 1503 1504
 1505 1506 1507 1508 1509 1510 1511 1512 1513 1514 1515 1516 1517 1518
 1519 1520 1521 1522 1523 1524 1525 1526 1527 1528 1529 1530 1531 1532
 1533 1534 1535 1536 1537 1538 1539 1540 1541 1542 1543 1544 1545 1546
 1547 1548 1549 1550 1551 1552 1553 1554 1555 1556 1557 1558 1559 1560
 1561 1562 1563 1564 1565 1566 1567]
['Aisha' 'Isabella' 'Chloe' 'Ravi' 'Kevin' 'Ethan' 'Fatima' 'Liam' 'David'
 'Grace' 'Emma' 'Ibrahim' 'Nathan' 'Zara' 'Maria' 'Olivia' 'Sophia'
 'Arjun' 'Noah' 'John']
[19. 20. 44. 27. 22. 58. 52. 21. 31. 47. 45. 49. 23. 51. 46. 32. 33. 59.
 26. 24. 60. 50. 37. 53. 29. 42. 43. 56. 36. 57. 39. 28. 54. 40. 48. 25.
 34. 35. 30. 18. 41. 55. 38.]
['F' 'M' 'male ']
['Chennai' 'Bengaluru' 'Ahmedabad' 'kochi ' 'Delhi' 'Kochi' 'Pune'
 'Mumbai' 'Hyderabad']
['Clothing' 'Books' 'Electronics' 'Home Decor' 'Grocery' 'electronics'
 'Toys' 'FASHION']
['Jeans' 'Magazine' 'Mobile' 'Lamp' 'Rice' 'Milk' 'Clock' 'Bread' 'Ball'
 'Textbook' 'Doll' 'Car' 'Headphones' 'Dress' 'Comics' 'Shirt' 'Tablet'
 'Cushion' 'Laptop' 'Novel' 'Curtain' 'Jacket' 'Puzzle' 'Oil']
[1 5 4 2 3]
[44448 39553 49829  6438 19313 56885 44020 42043  4437 17459 14473 39186
 49309 50035 35448  3896 43337 26248  1478  4517 37862 27859 16395 57410
 26734 51484  3932 33381 39062 17507 36996 24317 17432 13442 21959 35855
 59015 49217 52675 23015 50780 38149 59049 43631 36433 18903 33600 52958
 12842 52798 36729 17086 15467 46395 25624 56031 31927 38890 21553  1370
 55099 45940  1782 45791  4619 28640 55917 55868   765 29471 36372 15208
 47586 19909  6823 56573  9877 59639 41093   275 46170 59633 45233 48238
  2736 30902 18988 56782 49674  8057 14825 46329 12591 18636 50095 20952
 57390 30868 41177  6551 24665 57171 16833 19705 37581 48935 16525  6006
 32985 49524  8199  1740  7746  8990 40447 45036  6107 54482 56356 51872
  7548  2941 46787 41589 52076 26231  6078 27022 43139 55488 22370 48997
 51010 29139 28274  3690 32696 28688  7648 16045 21927  6837 49543 30831
 30360 38132  9986 34445  3531  5441 23863  5157 24788 29211 44553  3519
 29546  3590  6593 40427 19836 35230 37499 57334 15902 54520  2970 18850
 58730 28320 29323 28604  8372 24411 16458 14162 58995 55894 51897 58049
 20876 59784 34106 35062  2799 58361 45228 56558 17629 56808 57711  3412
 47777 25419 52194  2650 40278 53560 43064 53948 27163 21402 40081 45335
 53733 14123  3426 44742 21148  2481 18749 10749 40139 21307 47474 26669
  8853 44686 54414 44683 27325 48977 31037 24718 54810 22785  6712 35473
 19876 36528 24771 27145 29577 12431 48693 25047  6562  1162 15174 11125
 53708 14434 36252  7113 24548 26660 42364  3151 38571 21840 55063 32252
 46834  6097 29515 39293 34251 11058 39015 24996 20690 53609 28834 46973
  2509 42372 49045 45348 54581 28815 48628 41371   391 30086  7586 20624
 39187 19029 12887 11061 51266 54010 17323 40480 46240 56922 41545 29898
 28257 58699 28136  5501   171 53650  6863 34867 40475 51944 34031 15899
 27681 17282 42078 35252 28574 46073 48133 29931 58706 23953 47304 14726
 30033 32432 22803 32345 30145 43513 15409 20680  6025 23413 49126  8666
 59245 28487 18440 31493 52191 17823 23524 37828  1948 32241 38544  6721
 46445 11746  6922 29370 25392 54416 20987 58959 58410 19590 28123 41924
 42165 28918 43887 45127 37535 53083 17000 51647 36976 40008 45353 18472
 39747 20489 16450 44741 10816 42526 39496 16614 42524 44714 38309 55192
 42989 19370 34823 20834 29725 28523  1022  8549 29979 10905 24124  3261
 45660 47205 54593 45202  6003  3382 55887 17683 54868  6896 31759 46274
 22759 55729  3399 29466  2448 23912  6485 58877 14228 30075 51288 40011
 45976 44164 37497 44025 49487 25107 40769 44838 17417 10173 51482 22998
 54081 52280  2973 13913 30195 53945 44225 51669 10344 36375 13976 44073
  6535  4674 28169 57633 56376 38038 25822   794 37181 24311  2715 42939
 53658  5152 27272 16069 11001 39849 47560  1185 39409 34312 38703 57559
 42996 56131 51466 48320 52584 39437 26356 55842 15779  1107 12848  4843
 37007  4527 16369 58709 13651 44390 34554  7988 23797 12152 37547 12949
 19763 14220 36635 23372 42081 15056 34240 13900 50234 48438 56738 39263
 29057 18893 15252 54391 12420 21113 46971 20519  4778 50643 25601 23720
 38418 50614 46062 45270 19414 56963 24159 15749 18655 57345 34560 58411
 17520 47624 50319 26416 27123 29748 14641 10330 26301 42190 27397 35484
 49438 22131 40469 44123 11192 45015  1000 35910 11262 25570 46610 46792
 22826 58453 47934 20572 20350 20914 51159 45147 31154 48751 26633 30043
 19182  3674 27203 45432 40212 57038 41155 56160 26979 12213]
[20.  0.  5. 10. 15.]
['UPI' 'Net Banking' 'Cash' 'Debit Card' 'Credit Card' 'Credit card'
 <bound method NDFrame.ffill of 0              UPI
 1      Net Banking
 2             Cash
 3       Debit Card
 4       Debit Card
           ...
 567     Debit Card
 568           Cash
 569    Net Banking
 570     Debit Card
 571           Cash
 Name: Payment_Method, Length: 572, dtype: object>]
['2025-02-07' '2025-01-13' '2025-01-22' '2025-02-08' '2025-02-06'
 '2025-01-18' '2025-02-13' '2025-02-26' '2025-02-17' '2025-02-01'
 '2025-01-25' '2025-01-08' '2025-02-28' '2025-03-02' '2025-01-11'
 '2025-02-27' '2025-01-15' '2025-01-05' '2025-02-20' '2025-02-25'
 '2025-02-04' '2025-02-21' '2025-01-14' '2025-01-28' '2025-01-04'
 '2025-01-06' '2025-02-12' '2025-01-29' '2025-02-11' '2025-01-07'
 '2025-01-17' '2025-01-21' '2025-01-27' '2025-01-02' '2025-01-26'
 '2025-02-19' '2025-02-24' '2025-01-10' '2025-01-01' '2025-01-19'
 '2025-01-09' '2025-02-22' '2025-02-14' '2025-02-03' '2025-01-03'
 '2025-02-18' '2025-02-23' '2025-01-30' '2025-02-09' '2025-01-16'
 '2025-01-24' '2025-02-15' '2025-02-16' '2025-01-12' '2025-01-20'
 '2025-02-02' '2025-02-05' '2025-02-10' '2025-03-01' '2025-01-31'
 '2025-01-23']

In [12]:
df['Gender']=df['Gender'].replace('male ','M')

In [13]:
df.loc[df['City']=='kochi ','City']='Kochi'

In [14]:
df.isna().sum()

Order_ID            0
Customer_Name       0
Age                 0
Gender              0
City                0
Product_Category    0
Product             0
Quantity            0
Price               0
Discount (%)        0
Payment_Method      0
Order_Date          0
dtype: int64

In [15]:
#Which age group spends the most money overall? - 26
df1=df.groupby('Age')['Price'].sum().sort_values().tail(1)

In [16]:
df1

Age
26.0    905748
Name: Price, dtype: int64

In [17]:
#2. Do male or female customers purchase more on average? - F
dm=df.groupby('Gender')['Price'].mean()
dm

Gender
F    32145.398625
M    30298.295374
Name: Price, dtype: float64

In [18]:
#3. Which city contributes the highest revenue? - Delhi
DC=df.groupby('City')['Price'].sum().sort_values().tail(1)
DC

City
Delhi    2653085
Name: Price, dtype: int64

In [19]:
#4. Who are the top 5 customers by total spending? - sophia,chloe,aisha,grace,liam
dn=df.groupby('Customer_Name')['Price'].sum().sort_values(ascending=False).head()
dn

Customer_Name
Sophia    1331632
Chloe     1207785
Aisha     1187527
Grace     1083905
Liam      1037757
Name: Price, dtype: int64

In [20]:
#5. Which product category has the highest sales volume? - Books
dcc=df.groupby('Product_Category')['Quantity'].sum().sort_values().tail(1)
dcc

Product_Category
Books    365
Name: Quantity, dtype: int64

In [21]:
#6. What are the top 3 most sold products? - comics , milk , jacket
dp=df.groupby('Product')['Quantity'].sum().sort_values(ascending=False).head(3)
dp

Product
Comics      116
Textbook    102
Milk        101
Name: Quantity, dtype: int64

In [22]:
#What is the average discount given per product category?
dd=df.groupby('Product_Category')['Discount (%)'].mean()
dd

Product_Category
Books           9.960317
Clothing       11.208791
Electronics     9.829545
FASHION        15.000000
Grocery         9.784946
Home Decor     10.109890
Toys            9.382716
electronics    20.000000
Name: Discount (%), dtype: float64

In [27]:
df['og']=df['Quantity']*(df['Price']*((100-df['Discount (%)'])/100))

In [28]:
df

,Order_ID,Customer_Name,Age,Gender,City,Product_Category,Product,Quantity,Price,Discount (%),Payment_Method,Order_Date,og
0,1001,Aisha,19.0,F,Chennai,Clothing,Jeans,1,44448,20.0,UPI,2025-02-07,35558.40
1,1002,Isabella,20.0,M,Bengaluru,Clothing,Jeans,5,39553,0.0,Net Banking,2025-01-13,197765.00
2,1003,Chloe,44.0,M,Ahmedabad,Books,Magazine,1,49829,5.0,Cash,2025-01-22,47337.55
3,1004,Ravi,27.0,M,Kochi,Electronics,Mobile,4,6438,10.0,Debit Card,2025-02-08,23176.80
4,1005,Ravi,20.0,F,Bengaluru,Home Decor,Lamp,5,19313,20.0,Debit Card,2025-02-06,77252.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
567,1541,Ethan,26.0,M,Hyderabad,Clothing,Jeans,2,35910,20.0,Debit Card,2025-02-05,57456.00
568,1526,Sophia,26.0,M,Pune,Books,Magazine,3,29748,15.0,Cash,2025-01-01,75857.40
569,1235,Kevin,26.0,F,Pune,Toys,Car,1,12431,20.0,Net Banking,2025-01-14,9944.80
570,1527,Maria,26.0,M,Delhi,Grocery,Rice,3,14641,5.0,Debit Card,2025-01-02,41726.85
571,1491,Emma,26.0,F,Mumbai,Home Decor,Cushion,5,34240,15.0,Cash,2025-01-11,145520.00